name: responsive_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  responsive_framework: ^1.5.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/india.jpg
    - assets/images/moscow.jpg
    - assets/images/usa.jpg
    - assets/images/canada.jpg
    - assets/images/japan.jpg
    - assets/images/house/house1.jpg
    - assets/images/house/house2.jpg
    - assets/images/house/house3.jpg
    - assets/images/house/house4.jpg
    - assets/images/hosting.jpg
    - assets/images/house/house5.jpg
    - assets/images/house/house6.jpg
    - assets/images/house/house7.jpg
    - assets/images/house/house8.jpg
